import type { UiLocale } from "@callassist/contracts";

// Display copy for stable operational values; provider diagnostic codes remain verbatim.
const en = ["Completed", "Failed", "Stopped", "No answer", "Busy", "Canceled", "Ready", "Not assessed (no recording consent)", "Unavailable", "processing deadline reached", "Confirmed", "Not confirmed", "Attempt", "Shared", "Plan preparation", "Translation", "Summary and assessment", "Realtime AI", "Transcription", "Telephony", "AI", "Known subtotal", "usage estimate", "provider reported", "provider price pending", "usage unavailable", "partial estimate", "preliminary", "pending"];
const values: Record<UiLocale, string[]> = {
  en,
  de: ["Abgeschlossen", "Fehlgeschlagen", "Gestoppt", "Keine Antwort", "Besetzt", "Abgebrochen", "Bereit", "Nicht bewertet (keine Zustimmung zur Aufnahme)", "Nicht verfügbar", "Verarbeitungsfrist erreicht", "Bestätigt", "Nicht bestätigt", "Versuch", "Gemeinsam", "Planvorbereitung", "Übersetzung", "Zusammenfassung und Bewertung", "Echtzeit-KI", "Transkription", "Telefonie", "KI", "Bekannte Zwischensumme", "Nutzungsschätzung", "Vom Anbieter gemeldet", "Anbieterpreis ausstehend", "Nutzungsdaten fehlen", "Teilschätzung", "Vorläufig", "Ausstehend"],
  fr: ["Terminé", "Échec", "Arrêté", "Sans réponse", "Occupé", "Annulé", "Prêt", "Non évalué (enregistrement non autorisé)", "Indisponible", "délai de traitement atteint", "Confirmé", "Non confirmé", "Tentative", "Commun", "Préparation du plan", "Traduction", "Résumé et évaluation", "IA en temps réel", "Transcription", "Téléphonie", "IA", "Sous-total connu", "estimation d'utilisation", "communiqué par le fournisseur", "tarif du fournisseur en attente", "données d'utilisation indisponibles", "estimation partielle", "provisoire", "en attente"],
  it: ["Conclusa", "Non riuscita", "Interrotta", "Nessuna risposta", "Occupato", "Annullata", "Pronto", "Non valutato (nessun consenso alla registrazione)", "Non disponibile", "tempo di elaborazione scaduto", "Confermato", "Non confermato", "Tentativo", "Comune", "Preparazione del piano", "Traduzione", "Riepilogo e valutazione", "IA in tempo reale", "Trascrizione", "Telefonia", "IA", "Subtotale noto", "stima dell'utilizzo", "comunicato dal fornitore", "prezzo del fornitore in attesa", "dati di utilizzo non disponibili", "stima parziale", "provvisorio", "in attesa"],
  rm: ["Terminà", "Betg reussì", "Interrut", "Nagina resposta", "Occupà", "Annullà", "Pront", "Betg valità (nagin consentiment per la registraziun)", "Betg disponibel", "termin da l'elavuraziun cuntanschì", "Confermà", "Betg confermà", "Emprova", "Communabel", "Preparaziun dal plan", "Translaziun", "Resumaziun e valitaziun", "IA en temp real", "Transcripziun", "Telefonia", "IA", "Total parzial enconuschent", "stimaziun da l'utilisaziun", "annunzià dal purschider", "pretsch dal purschider pendent", "datas d'utilisaziun betg disponiblas", "stimaziun parziala", "provisoric", "pendent"],
  ru: ["Завершён", "Ошибка", "Остановлен", "Нет ответа", "Занято", "Отменён", "Готово", "Не оценивалось (нет согласия на запись)", "Недоступно", "время обработки истекло", "Подтверждено", "Не подтверждено", "Попытка", "Общие расходы", "Подготовка плана", "Перевод", "Итог и оценка", "ИИ в реальном времени", "Расшифровка", "Телефония", "ИИ", "Известная промежуточная сумма", "оценка по использованию", "данные провайдера", "ожидается цена провайдера", "данные использования недоступны", "частичная оценка", "предварительно", "ожидается"],
  uk: ["Завершено", "Помилка", "Зупинено", "Немає відповіді", "Зайнято", "Скасовано", "Готово", "Не оцінювалося (немає згоди на запис)", "Недоступно", "час обробки сплив", "Підтверджено", "Не підтверджено", "Спроба", "Спільні витрати", "Підготовка плану", "Переклад", "Підсумок та оцінка", "ШІ в реальному часі", "Розшифрування", "Телефонія", "ШІ", "Відома проміжна сума", "оцінка за використанням", "дані провайдера", "очікується ціна провайдера", "дані використання недоступні", "часткова оцінка", "попередньо", "очікується"]
};
export const notificationDetailMessages = Object.fromEntries(Object.entries(values).map(([locale, texts]) => [locale, Object.fromEntries(en.map((source, index) => [source.toLowerCase(), texts[index]!]))])) as Record<UiLocale, Record<string, string>>;
export function notificationDetail(value: string, locale: UiLocale): string {
  const copy = notificationDetailMessages[locale];
  const direct = copy[value.toLowerCase().replaceAll("_", " ").replace("no-answer", "no answer")];
  if (direct) return direct;
  // These delimiters separate display labels from diagnostic codes, not sentence fragments.
  return value.split(/( — | \/ |; |\(|\))/).map(part => copy[part.trim().toLowerCase()] ? `${part.startsWith(" ") ? " " : ""}${copy[part.trim().toLowerCase()]}${part.endsWith(" ") ? " " : ""}` : part).join("");
}
