import type { UiLocale } from "@callassist/contracts";

export const initialDisclosureMessages: Record<UiLocale, { title: string; warning: string; help: string; unavailable: string }> = {
  ru: { title: "Начальная реплика на языке звонка", warning: "Выбранная причина будет озвучена собеседнику до получения согласия на запись.", help: "Ассистент назовёт ваше полное имя и попросит разрешение на запись и автоматическую расшифровку.", unavailable: "Точный текст начальной реплики для этого звонка не сохранён." },
  uk: { title: "Початкова репліка мовою дзвінка", warning: "Обрану причину буде озвучено співрозмовнику до отримання згоди на запис.", help: "Асистент назве ваше повне ім’я та попросить дозвіл на запис і автоматичне розшифрування.", unavailable: "Точний текст початкової репліки для цього дзвінка не збережено." },
  en: { title: "Opening disclosure in the call language", warning: "The selected reason will be disclosed to the recipient before recording consent.", help: "The assistant will give your full name and ask permission to record and automatically transcribe the call.", unavailable: "The exact opening disclosure was not saved for this call." },
  de: { title: "Erste Ansage in der Anrufsprache", warning: "Der gewählte Grund wird vor der Zustimmung zur Aufzeichnung genannt.", help: "Die Assistenz nennt Ihren vollständigen Namen und bittet um Erlaubnis zur Aufzeichnung und automatischen Transkription.", unavailable: "Der genaue Wortlaut der ersten Ansage wurde für diesen Anruf nicht gespeichert." },
  fr: { title: "Annonce initiale dans la langue de l’appel", warning: "La raison choisie sera communiquée avant le consentement à l’enregistrement.", help: "L’assistant donnera votre nom complet et demandera l’autorisation d’enregistrer et de transcrire automatiquement l’appel.", unavailable: "Le texte exact de l’annonce initiale n’a pas été conservé pour cet appel." },
  it: { title: "Annuncio iniziale nella lingua della chiamata", warning: "Il motivo scelto sarà comunicato prima del consenso alla registrazione.", help: "L’assistente dirà il suo nome completo e chiederà il permesso di registrare e trascrivere automaticamente la chiamata.", unavailable: "Il testo esatto dell’annuncio iniziale non è stato salvato per questa chiamata." },
  rm: { title: "Annunzia iniziala en la lingua dal telefon", warning: "Il motiv tschernì vegn communitgà avant il consentiment a la registraziun.", help: "L’assistent numna Voss num cumplet e dumonda il permiss da registrar e transcriver automaticamain il telefon.", unavailable: "Il text exact da l’annunzia iniziala n’è betg vegnì memorisà per quest telefon." }
};
