import type { UiLocale } from "@callassist/contracts";
const en = {
  title: "Call plan preparation", scope: "The model and Fast mode apply to new preparations. Language checks and review translation keep their fixed profile.",
  model: "Generation model", fast: "Fast mode", fastHelp: "Fast mode costs more and shares rate limits with Standard. Only profiles with a reviewed quality report can be selected.",
  capacity: "Shared limits across all workers", generationSlots: "Active plans", reviewSlots: "Active review translations", providerSlots: "Provider requests", queueLimit: "Plans in the system", perUserWaiting: "Waiting plans per user", providerRequestsPerMinute: "Provider requests per minute", providerTokensPerMinute: "Provider tokens per minute", voiceReservePercent: "Quota reserved for calls (%)",
  reason: "Reason", save: "Save", refresh: "Refresh", saved: "Settings saved.", error: "Could not confirm settings. Refresh before retrying.",
  history: "Change history", admission: "Approve an evaluated profile", evidence: "SHA-256 of the reviewed report", reviewed: "I reviewed at least 200 cases with two runs each; no critical failures were found.", approve: "Approve profile", pending: "Evaluation required", restricted: "Only a superadmin can change settings.", revision: "Revision"
};
type Copy = typeof en;
export const preparationSettingsMessages: Record<UiLocale, Copy> = {
  en,
  ru: { title: "Подготовка плана звонка", scope: "Модель и Fast mode применяются к новым подготовкам. Проверка языка и перевод для просмотра сохраняют фиксированный профиль.", model: "Модель генерации", fast: "Fast mode", fastHelp: "Fast mode стоит дороже и использует общие со Standard квоты. Доступны только профили с проверенным отчётом о качестве.", capacity: "Общие лимиты всех воркеров", generationSlots: "Активные планы", reviewSlots: "Активные переводы плана", providerSlots: "Запросы к провайдеру", queueLimit: "Планы в системе", perUserWaiting: "Ожидающие планы пользователя", providerRequestsPerMinute: "Запросов провайдера в минуту", providerTokensPerMinute: "Токенов провайдера в минуту", voiceReservePercent: "Резерв квоты для звонков (%)", reason: "Причина", save: "Сохранить", refresh: "Обновить", saved: "Настройки сохранены.", error: "Не удалось подтвердить настройки. Обновите перед повтором.", history: "История изменений", admission: "Допуск проверенного профиля", evidence: "SHA-256 проверенного отчёта", reviewed: "Я проверил не менее 200 сценариев по два прогона; критических ошибок нет.", approve: "Допустить профиль", pending: "Нужна оценка качества", restricted: "Настройки может менять только суперадминистратор.", revision: "Ревизия" },
  uk: { title: "Підготовка плану дзвінка", scope: "Модель і Fast mode застосовуються до нових підготовок. Перевірка мови й переклад для перегляду зберігають фіксований профіль.", model: "Модель генерації", fast: "Fast mode", fastHelp: "Fast mode коштує дорожче та використовує спільні зі Standard квоти. Доступні лише профілі з перевіреним звітом про якість.", capacity: "Спільні ліміти всіх воркерів", generationSlots: "Активні плани", reviewSlots: "Активні переклади плану", providerSlots: "Запити до провайдера", queueLimit: "Плани в системі", perUserWaiting: "Плани користувача в черзі", providerRequestsPerMinute: "Запитів провайдера за хвилину", providerTokensPerMinute: "Токенів провайдера за хвилину", voiceReservePercent: "Резерв квоти для дзвінків (%)", reason: "Причина", save: "Зберегти", refresh: "Оновити", saved: "Налаштування збережено.", error: "Не вдалося підтвердити налаштування. Оновіть перед повтором.", history: "Історія змін", admission: "Допуск перевіреного профілю", evidence: "SHA-256 перевіреного звіту", reviewed: "Я перевірив щонайменше 200 сценаріїв по два прогони; критичних помилок немає.", approve: "Допустити профіль", pending: "Потрібна оцінка якості", restricted: "Налаштування може змінювати лише суперадміністратор.", revision: "Ревізія" },
  de: { title: "Vorbereitung des Anrufplans", scope: "Modell und Fast mode gelten für neue Vorbereitungen. Sprachprüfung und Übersetzung behalten ihr festes Profil.", model: "Generierungsmodell", fast: "Fast mode", fastHelp: "Fast mode kostet mehr und teilt Ratenlimits mit Standard. Nur Profile mit geprüftem Qualitätsbericht sind auswählbar.", capacity: "Gemeinsame Grenzen aller Worker", generationSlots: "Aktive Pläne", reviewSlots: "Aktive Planübersetzungen", providerSlots: "Anbieteranfragen", queueLimit: "Pläne im System", perUserWaiting: "Wartende Pläne je Nutzer", providerRequestsPerMinute: "Anbieteranfragen pro Minute", providerTokensPerMinute: "Anbietertokens pro Minute", voiceReservePercent: "Quotenreserve für Anrufe (%)", reason: "Grund", save: "Speichern", refresh: "Aktualisieren", saved: "Einstellungen gespeichert.", error: "Einstellungen nicht bestätigt. Vor erneutem Versuch aktualisieren.", history: "Änderungsverlauf", admission: "Geprüftes Profil freigeben", evidence: "SHA-256 des geprüften Berichts", reviewed: "Ich habe mindestens 200 Fälle mit je zwei Durchläufen geprüft; keine kritischen Fehler.", approve: "Profil freigeben", pending: "Qualitätsprüfung erforderlich", restricted: "Nur Superadmins können Einstellungen ändern.", revision: "Revision" },
  fr: { title: "Préparation du plan d’appel", scope: "Le modèle et Fast mode s’appliquent aux nouvelles préparations. Le contrôle linguistique et la traduction conservent leur profil fixe.", model: "Modèle de génération", fast: "Fast mode", fastHelp: "Fast mode coûte plus cher et partage les limites de Standard. Seuls les profils avec un rapport qualité vérifié sont disponibles.", capacity: "Limites communes à tous les workers", generationSlots: "Plans actifs", reviewSlots: "Traductions actives", providerSlots: "Requêtes au fournisseur", queueLimit: "Plans dans le système", perUserWaiting: "Plans en attente par utilisateur", providerRequestsPerMinute: "Requêtes fournisseur par minute", providerTokensPerMinute: "Tokens fournisseur par minute", voiceReservePercent: "Quota réservé aux appels (%)", reason: "Motif", save: "Enregistrer", refresh: "Actualiser", saved: "Réglages enregistrés.", error: "Réglages non confirmés. Actualisez avant de réessayer.", history: "Historique des modifications", admission: "Approuver un profil évalué", evidence: "SHA-256 du rapport vérifié", reviewed: "J’ai vérifié au moins 200 cas avec deux essais chacun ; aucune erreur critique.", approve: "Approuver le profil", pending: "Évaluation requise", restricted: "Seul un superadmin peut modifier les réglages.", revision: "Révision" },
  it: { title: "Preparazione del piano di chiamata", scope: "Il modello e Fast mode valgono per nuove preparazioni. Verifica linguistica e traduzione mantengono il profilo fisso.", model: "Modello di generazione", fast: "Fast mode", fastHelp: "Fast mode costa di più e condivide i limiti con Standard. Sono disponibili solo profili con rapporto qualità verificato.", capacity: "Limiti condivisi da tutti i worker", generationSlots: "Piani attivi", reviewSlots: "Traduzioni attive", providerSlots: "Richieste al fornitore", queueLimit: "Piani nel sistema", perUserWaiting: "Piani in attesa per utente", providerRequestsPerMinute: "Richieste fornitore al minuto", providerTokensPerMinute: "Token fornitore al minuto", voiceReservePercent: "Quota riservata alle chiamate (%)", reason: "Motivo", save: "Salva", refresh: "Aggiorna", saved: "Impostazioni salvate.", error: "Impostazioni non confermate. Aggiorna prima di riprovare.", history: "Cronologia delle modifiche", admission: "Approva un profilo valutato", evidence: "SHA-256 del rapporto verificato", reviewed: "Ho verificato almeno 200 casi con due prove ciascuno; nessun errore critico.", approve: "Approva profilo", pending: "Valutazione necessaria", restricted: "Solo un superadmin può modificare le impostazioni.", revision: "Revisione" },
  rm: { title: "Preparaziun dal plan da clom", scope: "Il model e Fast mode valan per novas preparaziuns. La controlla linguistica e la translaziun mantegnan lur profil fix.", model: "Model da generaziun", fast: "Fast mode", fastHelp: "Fast mode custa dapli e parta ils limits cun Standard. Mo profils cun in rapport da qualitad examinà èn disponibels.", capacity: "Limits communabels da tut ils workers", generationSlots: "Plans activs", reviewSlots: "Translaziuns activas", providerSlots: "Dumondas al purschider", queueLimit: "Plans en il sistem", perUserWaiting: "Plans en spetga per utilisader", providerRequestsPerMinute: "Dumondas al purschider per minuta", providerTokensPerMinute: "Tokens dal purschider per minuta", voiceReservePercent: "Quota reservada per cloms (%)", reason: "Motiv", save: "Memorisar", refresh: "Actualisar", saved: "Parameters memorisads.", error: "Parameters betg confermads. Actualisai avant da reempruvar.", history: "Istorgia da las midadas", admission: "Admetter in profil evaluà", evidence: "SHA-256 dal rapport examinà", reviewed: "Jau hai examinà almain 200 cas cun mintgamai duas emprovas; nagins sbagls critics.", approve: "Admetter il profil", pending: "Evaluaziun necessaria", restricted: "Mo in superadmin po midar ils parameters.", revision: "Revisiun" }
};
