const $=id=>document.getElementById(id);
let settings={id:'landing',state:'default',theme:'light',lang:'en',width:'fluid',...Object.fromEntries(new URLSearchParams(location.hash.slice(1)))};
function screen(){return SCREENS.find(x=>x.id===settings.id)||SCREENS[0]}
function renderNav(){let group='';$('screen-nav').innerHTML=SCREENS.map(x=>{let heading=x.group!==group?`<h2>${x.group}</h2>`:'';group=x.group;return heading+`<a href="#id=${x.id}" data-id="${x.id}" class="${x.id===settings.id?'active':''}">${x.title}</a>`}).join('');$('mobile-screen').innerHTML=SCREENS.map(x=>`<option value="${x.id}">${x.title}</option>`).join('');$('mobile-screen').value=settings.id;document.querySelectorAll('[data-id]').forEach(a=>a.onclick=e=>{e.preventDefault();settings.id=a.dataset.id;settings.state=screen().states[0];update(true)})}
function update(nav=false){Object.assign(settings,resolveDesignScreen(settings.id,settings.state));const s=screen();settings.id=s.id;if(!s.states.includes(settings.state))settings.state=s.states[0];if(nav)renderNav();$('state').innerHTML=s.states.map(x=>`<option>${x}</option>`).join('');for(const id of ['state','theme','width','lang'])$(id).value=settings[id];$('lang').disabled=s.id.startsWith('admin-');$('frame-wrap').style.width=settings.width==='fluid'?'100%':settings.width+'px';const q=new URLSearchParams({id:s.id,state:settings.state,theme:settings.theme,lang:settings.lang,v:'02'});const url='mock.html?'+q;$('preview').src=url;$('open-frame').href=url;$('screen-title').textContent=s.title;$('route').textContent=s.route;$('source').textContent='Источник: apps/web/components/'+s.source;history.replaceState(null,'','#'+new URLSearchParams(settings));}
for(const id of ['state','theme','width','lang'])$(id).onchange=()=>{settings[id]=$(id).value;update()};$('mobile-screen').onchange=()=>{settings.id=$('mobile-screen').value;settings.state=screen().states[0];update(true)};
window.addEventListener('message',e=>{if(e.source!==$('preview').contentWindow||e.data?.type!=='design-navigation')return;Object.assign(settings,e.data.settings);update(true)});update(true);

window.addEventListener('message',e=>{if(e.source!==$('preview').contentWindow)return;if(e.data?.type==='design-theme'){settings.theme=e.data.theme;$('theme').value=settings.theme}else if(e.data?.type==='design-state'){settings.state=e.data.state;$('state').value=settings.state}else return;const q=new URLSearchParams({id:settings.id,state:settings.state,theme:settings.theme,lang:settings.lang,v:'02'});$('open-frame').href='mock.html?'+q;history.replaceState(null,'','#'+new URLSearchParams(settings))});
