function navigate(id=ctx.id,s='default'){({id,state:s}=resolveDesignScreen(id,s));const settings={id,state:s,theme:ctx.theme,lang:ctx.lang,v:'02'};if(window.parent!==window)window.parent.postMessage({type:'design-navigation',settings},'*');else location.href='mock.html?'+new URLSearchParams(settings)}
function render(){fieldIndex=0;if(ctx.id.startsWith('admin-'))ctx.lang='en';document.documentElement.dataset.theme=ctx.theme;document.documentElement.lang=ctx.lang;const renderers={landing:landingPage,'preview-landing':landingPage,register:authPage,login:authPage,verify:authPage,recover:authPage,onboarding:authPage,'new-call':dashboardPage,call:callPage,'call-completed':callPage,account:accountPage,redeem:smallFlow,'opt-out':smallFlow,faq:docPage,support:docPage,privacy:docPage,terms:docPage,'acceptable-use':docPage,imprint:docPage,'preview-content':docPage,error:errorPage,components:componentsPage};document.getElementById('app').innerHTML=ctx.id.startsWith('admin-')?adminPage():(renderers[ctx.id]||errorPage)();if(!document.querySelector('#app > .footer'))document.getElementById('app').insertAdjacentHTML('beforeend',footer());document.title='SHPROHLI · '+(SCREENS.find(x=>x.id===ctx.id)?.title||'Design');const dialog=document.querySelector('[role=dialog]');if(dialog){dialog.focus();const all=[...dialog.querySelectorAll('input')];if(all.length){const action=dialog.querySelector('.actions button:last-child');const update=()=>{const phrase=ctx.id==='account'?'DELETE MY ACCOUNT':'DELETE';action.disabled=!all.every(x=>x.value.trim())||(all.length>1&&all.at(-1).value!==phrase)};all.forEach(x=>x.addEventListener('input',update));update()}}if(ctx.id==='new-call'||ctx.state==='edit'){const call=document.getElementById('call-form');if(call){const required=[...call.querySelectorAll('[required]')];const update=()=>{const n=required.filter(x=>x.value.trim()).length;document.querySelector('[data-progress]').textContent=n+'/5';document.querySelector('[data-progress-help]').textContent=n+'/5 '+T('required fields completed','Pflichtfelder ausgefüllt');document.querySelector('.progress-track i').style.width=(n/5*100)+'%';call.querySelector('[type=submit]').disabled=n!==5||['preparing','no-credits','active-call','paused'].includes(ctx.state)};call.addEventListener('input',update);update()}}}
function toast(text){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),4500)}
document.addEventListener('click',e=>{const target=e.target.closest('button,a');if(!target)return;if(target.hasAttribute('data-theme-toggle')){applyMockTheme(ctx.theme==='dark'?'light':'dark');return}if(target.hasAttribute('data-audio-toggle')){target.textContent=target.textContent===T('Pause','Pause')?T('Play','Start'):T('Pause','Pause');return}if(target.dataset.page||target.dataset.state){e.preventDefault();navigate(target.dataset.page||ctx.id,target.dataset.state||'default');return}if(target.dataset.demo){e.preventDefault();if(/Copy transcript|Transkript kopieren/.test(target.textContent)&&navigator.clipboard){navigator.clipboard.writeText(document.querySelector('.transcript')?.innerText||'Demo transcript').then(()=>toast(T('Demo transcript copied.','Beispieltranskript kopiert.'))).catch(()=>toast('Copy action · design preview'));}else if(/Add section/.test(target.textContent)){const item=document.createElement('div');item.className='editor-item';item.innerHTML='<h3>New section</h3><div class="stack">'+field('Heading','')+field('Paragraphs (one per line)','',{type:'textarea'})+'</div>';target.before(item)}else if(/Remove section/.test(target.textContent))target.closest('.editor-item')?.remove();else toast(T('Design preview: this action has no connection to the service.','Designvorschau: Diese Aktion hat keine Verbindung zum Dienst.'));}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target;if(form.hasAttribute('data-feedback-form')){saveMockFeedback(form);return}if(form.reportValidity())navigate(form.dataset.page||ctx.id,form.dataset.next||'default')});
document.addEventListener('change',e=>{if(e.target.hasAttribute('data-language')){ctx.lang=e.target.value.toLowerCase();navigate(ctx.id,ctx.state)}});
document.addEventListener('keydown',e=>{const dialog=document.querySelector('[role=dialog]');if(!dialog)return;if(e.key==='Escape'){const cancel=dialog.querySelector('.actions button');navigate(cancel.dataset.page||ctx.id,cancel.dataset.state||'default')}if(e.key==='Tab'){const focusable=[...dialog.querySelectorAll('button:not(:disabled),a,input,textarea,select')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
function setupMockControls(){const filters=document.querySelector('.filter-panel');if(filters){const media=matchMedia('(min-width:768px)');filters.open=media.matches;media.addEventListener('change',e=>filters.open=e.matches)}const call=document.getElementById('call-form');if(call){const selects=[...call.querySelectorAll('select')];const reason=selects.find(x=>x.closest('label').textContent.includes(T('Reason for assistance','Grund der Unterstützung')));if(reason){const help=reason.closest('label').querySelector('small');const toggle=()=>{help.hidden=reason.selectedIndex===0};reason.addEventListener('change',toggle);toggle()}const result=selects.find(x=>x.closest('label').textContent.startsWith(T('Result','Ergebnis')));const delivery=[...call.querySelectorAll('label.field')].find(x=>x.textContent.startsWith(T('Delivery instruction','Übermittlungsanweisung')));if(result&&delivery){const toggle=()=>delivery.hidden=result.selectedIndex!==1;result.addEventListener('change',toggle);toggle()}const fallback=selects.find(x=>x.closest('label').textContent.startsWith(T('Fallback language','Ausweichsprache')));const switching=call.querySelector('input[type=checkbox]');if(fallback&&switching){const toggle=()=>fallback.closest('label').hidden=!switching.checked;switching.addEventListener('change',toggle);toggle()}for(const area of call.querySelectorAll('textarea[maxlength]')){const helper=area.closest('label').querySelector('small');if(helper){const update=()=>helper.textContent=area.value.length+' / '+area.maxLength+' '+T('characters','Zeichen');area.addEventListener('input',update);update()}}}const history=document.querySelector('.history');if(history){const search=history.querySelector('input[type=search]'),status=history.querySelector('select');const filter=()=>{for(const row of history.querySelectorAll('.history-item'))row.hidden=!(row.textContent.toLowerCase().includes(search.value.toLowerCase())&&(status.selectedIndex===0||row.textContent.includes(status.value)))};search.addEventListener('input',filter);status.addEventListener('change',filter)}}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-state]');if(!b||b.closest('[role=dialog]'))return;const guarded=ctx.id==='admin-users'&&['suspend','restore','force-logout','grant','restart-deletion'].includes(b.dataset.state)||['admin-content','admin-editorial'].includes(ctx.id)&&['publish','rollback'].includes(b.dataset.state);if(guarded){const area=b.closest('section,form')?.querySelector('textarea');if(area){area.required=true;area.minLength=3;if(!area.reportValidity()){e.preventDefault();e.stopImmediatePropagation()}}}},true);
render();setupMockControls();setupRevisionControls();

function applyMockTheme(theme){
 ctx.theme=theme;document.documentElement.dataset.theme=theme;
 document.querySelectorAll('.logo').forEach(i=>i.src='assets/logo-'+theme+'.svg');
 document.querySelectorAll('[data-theme-toggle]').forEach(b=>{const label=theme==='dark'?T('Switch to light theme','Zur hellen Ansicht wechseln'):T('Switch to dark theme','Zur dunklen Ansicht wechseln');b.innerHTML=icon(theme==='dark'?'sun':'moon');b.setAttribute('aria-label',label);b.title=label});
 document.querySelectorAll('a[href]').forEach(a=>{if(a.getAttribute('href').startsWith('#'))return;const url=new URL(a.href);if(url.pathname.endsWith('/mock.html')){url.searchParams.set('theme',theme);a.href=url.pathname.split('/').at(-1)+url.search+url.hash}});
 const url=new URL(location.href);url.searchParams.set('theme',theme);history.replaceState(null,'',url);
 if(window.parent!==window)window.parent.postMessage({type:'design-theme',theme},'*');
}
function setupRevisionControls(){
 const menu=document.querySelector('.mobile-menu');if(menu){const button=menu.querySelector('summary');menu.addEventListener('toggle',()=>{button.setAttribute('aria-expanded',String(menu.open));const label=menu.open?T('Close menu','Menü schliessen'):T('Open menu','Menü öffnen');button.setAttribute('aria-label',label);button.title=label});document.addEventListener('click',e=>{if(menu.open&&!menu.contains(e.target))menu.open=false});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.open&&!document.querySelector('[role=dialog]')){menu.open=false;button.focus()}})}
 const feedback=document.querySelector('[data-feedback-form]');if(feedback){const comment=feedback.querySelector('textarea'),counter=feedback.querySelector('[data-feedback-count]');const update=()=>{feedback.querySelector('[type=submit]').disabled=!feedback.querySelector('[name=goal-result]:checked');counter.textContent=comment.value.length+' / 500';};feedback.addEventListener('input',update);update()}
}
function saveMockFeedback(form){
 if(!form.reportValidity())return;
 const selected=form.querySelector('[name=goal-result]:checked');if(!selected)return;
 form.querySelector('[data-feedback-status]').textContent=T('Your feedback was saved.','Ihre Rückmeldung wurde gespeichert.');
 form.querySelector('[type=submit]').textContent=T('Update feedback','Rückmeldung aktualisieren');
 ctx.state='feedback-saved';const url=new URL(location.href);url.searchParams.set('state',ctx.state);history.replaceState(null,'',url);
 if(window.parent!==window)window.parent.postMessage({type:'design-state',id:ctx.id,state:ctx.state},'*');
}
