const ctx={id:'landing',state:'default',theme:'light',lang:'en',...Object.fromEntries(new URLSearchParams(location.search))};
Object.assign(ctx,resolveDesignScreen(ctx.id,ctx.state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const T=(en,de)=>ctx.lang==='de'&&de?de:en;
const state=s=>ctx.state===s;
let fieldIndex=0;
function href(id,s='default'){({id,state:s}=resolveDesignScreen(id,s));return 'mock.html?'+new URLSearchParams({id,state:s,theme:ctx.theme,lang:ctx.lang,v:'02'})}
function link(label,id,s='default',cls=''){return `<a class="${cls}" href="${href(id,s)}" data-page="${resolveDesignScreen(id,s).id}" data-state="${resolveDesignScreen(id,s).state}">${label}</a>`}
function btn(label,s='',cls='',page=''){return `<button type="button" class="${cls}" ${s?`data-state="${s}"`:''} ${page?`data-page="${page}"`:''} ${!s&&!page?'data-demo="true"':''}>${label}</button>`}
function submit(label,disabled=false){return `<button class="primary" type="submit" ${disabled?'disabled':''}>${label}</button>`}
function field(label,value='',o={}){const id='field-'+(++fieldIndex);let attrs=`id="${id}" name="${id}" ${o.required?'required':''} ${o.disabled?'disabled':''} ${o.minLength?`minlength="${o.minLength}"`:''} ${o.maxLength?`maxlength="${o.maxLength}"`:''} ${o.numeric?'inputmode="numeric"':''} ${o.error?'aria-invalid="true"':''} ${o.help||o.error?`aria-describedby="${id}-help"`:''}`;let control=o.options?`<select ${attrs}>${o.options.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`:o.type==='textarea'?`<textarea ${attrs} rows="${o.rows||4}" placeholder="${esc(o.placeholder||'')}">${esc(value)}</textarea>`:`<input ${attrs} type="${o.type||'text'}" value="${esc(value)}" placeholder="${esc(o.placeholder||'')}" ${o.type==='number'?'min="1"':''} autocomplete="off">`;return `<label class="field" for="${id}"><span>${label}${o.optional?' <span class="muted">'+T('(optional)','(optional)')+'</span>':''}</span>${control}${o.help||o.error?`<small id="${id}-help" class="${o.error?'field-error':''}">${o.error||o.help}</small>`:''}</label>`}
function check(label,checked=false,required=false){return `<label class="check"><input type="checkbox" ${checked?'checked':''} ${required?'required':''}><span>${label}</span></label>`}
function form(content,s,page=''){return `<form class="stack native-form" data-next="${s}" ${page?`data-page="${page}"`:''}>${content}</form>`}
const note=(text,type='')=>`<div class="note ${type}" role="${type==='error'?'alert':'status'}">${text}</div>`;
const badge=(text,type='')=>`<span class="badge ${type}">${text}</span>`;
const intro=(title,text='',eyebrow='')=>`<header class="intro">${eyebrow?`<span class="eyebrow">${eyebrow}</span>`:''}<h1>${title}</h1>${text?`<p class="muted">${text}</p>`:''}</header>`;
const section=(title,body,id='')=>`<section class="section" ${id?`id="${id}"`:''}><h2>${title}</h2>${body}</section>`;
function facts(rows){return `<dl class="facts">${rows.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`}
function table(heads,rows,responsive=true){return `<div class="table-wrap"><table class="table ${responsive?'responsive':''}"><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td data-label="${esc(heads[i])}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function empty(title,text,action=''){return `<div class="empty"><h2>${title}</h2><p class="muted">${text}</p>${action}</div>`}
function segmented(label,options){const n='radio-'+(++fieldIndex);return `<fieldset style="border:0;padding:0;margin:0"><legend style="margin-bottom:10px;font-size:14px">${label}</legend><div class="segmented">${options.map((x,i)=>`<label><input type="radio" name="${n}" value="${esc(x)}"><span>${x}</span></label>`).join('')}</div></fieldset>`}
function modal(title,text,content='',action='Confirm',next='default',danger=false,cancel='default'){return `<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1"><h2 id="dialog-title">${title}</h2><p>${text}</p>${content}<div class="actions">${btn(T('Cancel','Abbrechen'),cancel)}${btn(action,next,danger?'danger':'primary')}</div></div></div>`}
function languageControl(){return ctx.id.startsWith('admin-')?'':`<select aria-label="${T('Interface language','Oberflächensprache')}" data-language><option ${ctx.lang==='en'?'selected':''}>EN</option><option ${ctx.lang==='de'?'selected':''}>DE</option></select>`}
function icon(name,extra=''){return HERO_ICONS[name].replace('<svg',`<svg class="ui-icon ${extra}" width="24" height="24" aria-hidden="true" focusable="false"`)}
function themeButton(){const label=ctx.theme==='dark'?T('Switch to light theme','Zur hellen Ansicht wechseln'):T('Switch to dark theme','Zur dunklen Ansicht wechseln');return `<button type="button" class="icon-button" data-theme-toggle aria-label="${label}" title="${label}">${icon(ctx.theme==='dark'?'sun':'moon')}</button>`}
function themeTools(){return `<div class="tools">${ctx.id.startsWith('admin-')?'':link(T('2 call credits','2 Anrufguthaben'),'account','usage','credits')}${themeButton()}${languageControl()}</div>`}
function header(kind='public'){
 const admin=kind==='admin',signed=kind==='customer';
 const publicLinks=`<a href="${href('landing')}#how-it-works">${T('How it works','So funktioniert es')}</a>${link('FAQ','faq')}${link(T('Support','Hilfe'),'support')}`;
 const more=`${link(T('Redeem code','Code einlösen'),'redeem')}${link(T('Block calls','Anrufe blockieren'),'opt-out')}${link('FAQ','faq')}${link(T('Support','Hilfe'),'support')}${link('Admin','admin-overview')}`;
 const customerLinks=`${link(T('New call','Neuer Anruf'),'new-call','default',ctx.id==='new-call'?'active':'')}${link(T('History','Verlauf'),'new-call','history',ctx.id.startsWith('call')?'active':'')}${link(T('Account','Konto'),'account','default',ctx.id==='account'?'active':'')}`;
 const nav=signed?customerLinks+`<details class="dropdown"><summary>${T('More','Mehr')}</summary><nav>${more}</nav></details>`:publicLinks;
 const mobileNav=admin?adminLinks()+link('Customer app','new-call')+link('Sign out','login'):signed?customerLinks+more:publicLinks+link(T('Block calls','Anrufe blockieren'),'opt-out')+link(T('Sign in','Anmelden'),'login')+link(T('Create account','Konto erstellen'),'register');
 return `<a class="skip" href="#main-content">${T('Skip to main content','Zum Hauptinhalt')}</a><header class="topbar"><div class="brand">${link(`<img class="logo" src="assets/logo-${ctx.theme}.svg" alt="SHPROHLI">`,admin?'admin-overview':'landing')}${admin?'<span class="admin-label">Admin</span>':''}</div>${admin?`<div class="toplinks"><div><strong>Alex Morgan</strong><br><small>Superadmin</small></div>${link('Customer app','new-call')}${btn('Sign out','default','','login')}</div>`:`<nav class="toplinks" aria-label="${T('Main navigation','Hauptnavigation')}">${nav}</nav>`}${!signed&&!admin?`<div class="tools">${link(T('Sign in','Anmelden'),'login')}${link(T('Create account','Konto erstellen'),'register','default','button primary')}${themeButton()}${languageControl()}</div>`:themeTools()}<div class="mobile-actions">${themeButton()}<details class="dropdown mobile-menu"><summary class="icon-button" aria-label="${T('Open menu','Menü öffnen')}" title="${T('Open menu','Menü öffnen')}" aria-controls="mobile-navigation" aria-expanded="false">${icon('bars-3','menu-closed-icon')}${icon('x-mark','menu-open-icon')}</summary><nav id="mobile-navigation" aria-label="${T('Main navigation','Hauptnavigation')}">${mobileNav}${!admin?'<div class="menu-language">'+languageControl()+'</div>':''}</nav></details></div></header>`;
}
function footer(){return `<footer class="footer"><div><strong>SHPROHLI</strong><p class="muted">${T('Public beta','Öffentliche Beta')}</p></div><nav aria-label="Product">${link('FAQ','faq')}${link(T('Support','Hilfe'),'support')}${link(T('Block calls','Anrufe blockieren'),'opt-out')}</nav><nav aria-label="Legal">${link(T('Privacy','Datenschutz'),'privacy')}${link(T('Terms','Bedingungen'),'terms')}${link(T('Acceptable Use','Nutzungsregeln'),'acceptable-use')}${link(T('Imprint','Impressum'),'imprint')}</nav></footer>`}
function adminLinks(){return `<span class="eyebrow">Operations</span>${[['Overview','admin-overview'],['Calls','admin-calls'],['Users','admin-users'],['Credits','admin-credits'],['Safety','admin-safety'],['System','admin-system']].map(([l,id])=>link(l,id,'default',ctx.id===id?'active':'')).join('')}<span class="eyebrow">Content</span>${[['Pages','admin-content'],['Editorial','admin-editorial'],['SEO','admin-seo']].map(([l,id])=>link(l,id,'default',ctx.id===id?'active':'')).join('')}`}
function previewBanner(){return `<div class="preview-banner" role="status"><div><strong>${T('Private draft preview','Private Entwurfsvorschau')}</strong> · ${T('Not visible to the public','Nicht öffentlich sichtbar')}</div>${link(T('Back to editor','Zurück zum Editor'),ctx.id==='preview-landing'?'admin-editorial':'admin-content')}</div>`}
